CREATE DATABASE BANKING_SYSTEM; -- Created Database
USE BANKING_SYSTEM; -- Acces the database

CREATE TABLE CUSTOMERS(
CUSTOMERID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAILID VARCHAR(100),
PHONE  VARCHAR(10));

DESCRIBE TABLE CUSTOMERS;
DESCRIBE CUSTOMERS;
select*
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN ACCOUNTCREATIONDATE DATE;

CREATE TABLE ACCOUNTS(
ACCOUNTID INT,
ACCOUNTTYPE VARCHAR(20),
BALANCE DECIMAL(10,2));

CREATE TABLE TRANSACTIONS(
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20));

CREATE TABLE BRANCHES(
BARNCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(255),
BRANCHPHONENO VARCHAR (20));

CREATE TABLE ACCOUNTBRANCHES(
ASSIGNDATE DATE);

CREATE TABLE LOANS(
LOANID INT,
LOANAMOUNT DECIMAL(10,2),
INTRESTRATE DECIMAL (5,2),
STARTDATE DATE,
ENDDATE DATE);

SHOW TABLES; 

DROP TABLE TRANSACTIONID;
SHOW TABLES;

ALTER TABLE CUSTOMERS
DROP COLUMN	ACCOUNTCREATIONDATE;

select*
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN BIRTHDATE DATE;

ALTER TABLE CUSTOMERS
MODIFY PHONE VARCHAR(20),
ADD PRIMARY KEY(CUSTOMERID);

DESCRIBE CUSTOMERS;

DROP TABLE  ACCOUNTBRANCHES;

SHOW tables;

select*
FROM ACCOUNTS;
ALTER TABLE ACCOUNTS
ADD CUSTOMERID INT;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT 
foreign key (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

describe ACCOUNTS;

ALTER TABLE TRANSACTIONS
ADD ACCOUNTID INT;

ALTER TABLE TRANSACTIONS
ADD ACCOUNTID INT,
ADD constraint
foreign key (ACCOUNTID)
references ACCOUNTS(ACCOUNTID);

descRIBE TRANSACTIONS;

alter TABLE TRANSACTIONS
ADD PRIMARY KEY (TRANSACTIONID);

DESCRIBE ACCOUNTS;
ALTER TABLE ACCOUNTS 
ADD PRIMARY KEY (ACCOUNTID);

ALTER TABLE TRANSACTIONS
ADD constraint
foreign key (ACCOUNTID)
references ACCOUNTS(ACCOUNTID);

ALTER TABLE BRANCHES
ADD PRIMARY KEY (BARNCHID);
DESCRIBE BRANCHES;

ALTER TABLE ACCOUNTS
ADD BRANCHID INT,
ADD constraint
foreign key (BRANCHID)
references BRANCHES(BARNCHID);

ALTER TABLE LOANS
ADD PRIMARY KEY (LOANID),
ADD CUSTOMERID int,
ADD constraint
foreign key(CUSTOMERID)
references CUSTOMERS(CUSTOMERID);

describe LOANS;

ALTER TABLE CUSTOMERS 
MODIFY FIRSTNAME VARCHAR(50) NOT NULL,
MODIFY EMAILID VARCHAR(100) UNIQUE;
describe CUSTOMERS;



