CREATE DATABASE BANKING_SYSTEM; -- Created Database
USE BANKING_SYSTEM; -- Acces the database

CREATE TABLE CUSTOMERS(
CUSTOMERID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAILID VARCHAR(100),
PHONE  VARCHAR(10));

DESCRIBE TABLE CUSTOMERS;
DESCRIBE CUSTOMERS;
select*
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN ACCOUNTCREATIONDATE DATE;                 -- modify the column use ALTER

CREATE TABLE ACCOUNTS(
ACCOUNTID INT,
ACCOUNTTYPE VARCHAR(20),
BALANCE DECIMAL(10,2));

CREATE TABLE TRANSACTIONS(
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20));

CREATE TABLE BRANCHES(
BARNCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(255),
BRANCHPHONENO VARCHAR (20));

CREATE TABLE ACCOUNTBRANCHES(
ASSIGNDATE DATE);

CREATE TABLE LOANS(
LOANID INT,
LOANAMOUNT DECIMAL(10,2),
INTRESTRATE DECIMAL (5,2),
STARTDATE DATE,
ENDDATE DATE);

SHOW TABLES; 

DROP TABLE TRANSACTIONID;
SHOW TABLES;

ALTER TABLE CUSTOMERS
DROP COLUMN	ACCOUNTCREATIONDATE;

select*
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN BIRTHDATE DATE;

ALTER TABLE CUSTOMERS
MODIFY PHONE VARCHAR(20),
ADD PRIMARY KEY(CUSTOMERID);

DESCRIBE CUSTOMERS;

DROP TABLE  ACCOUNTBRANCHES;

SHOW tables;

select*
FROM ACCOUNTS;
ALTER TABLE ACCOUNTS
ADD CUSTOMERID INT;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT 
foreign key (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

describe ACCOUNTS;

ALTER TABLE TRANSACTIONS
ADD ACCOUNTID INT;

ALTER TABLE TRANSACTIONS
ADD ACCOUNTID INT,
ADD constraint
foreign key (ACCOUNTID)
references ACCOUNTS(ACCOUNTID);

descRIBE TRANSACTIONS;

alter TABLE TRANSACTIONS
ADD PRIMARY KEY (TRANSACTIONID);

DESCRIBE ACCOUNTS;
ALTER TABLE ACCOUNTS 
ADD PRIMARY KEY (ACCOUNTID);

ALTER TABLE TRANSACTIONS
ADD constraint
foreign key (ACCOUNTID)
references ACCOUNTS(ACCOUNTID);

ALTER TABLE BRANCHES
ADD PRIMARY KEY (BARNCHID);
DESCRIBE BRANCHES;

ALTER TABLE ACCOUNTS
ADD BRANCHID INT,
ADD constraint
foreign key (BRANCHID)
references BRANCHES(BARNCHID);

ALTER TABLE LOANS
ADD PRIMARY KEY (LOANID),
ADD CUSTOMERID int,
ADD constraint
foreign key(CUSTOMERID)
references CUSTOMERS(CUSTOMERID);

describe LOANS;

ALTER TABLE CUSTOMERS 
MODIFY FIRSTNAME VARCHAR(50) NOT NULL,
MODIFY EMAILID VARCHAR(100) UNIQUE;
describe CUSTOMERS;

-- Adding Records inside the tables

INSERT INTO CUSTOMERS
VALUES (101,'RAHUL','SAHRMA','rahul.sharma@gmail.com','5478934256','1995-04-12');

SELECT *
FROM CUSTOMERS;

INSERT INTO CUSTOMERS
VALUES (102,'SURAJ','THANGE','suraj.thange@gmail.com','5478945987','1995-08-03'),
(103,'SAMYAK','UBALE','samyak.ubale@gmail.com','8732045987',NULL),
(104,'JITESH','BHOIR','jitesh.bhoir@gmail.com','5496320987','1995-01-09'),
(105,'AJIT','PASHTE','ajit.pashte@gmail.com',NULL,'1995-07-10');

-- INSERT INTO CUSTOMERS
-- VALUE (NULL,'SURAJ','THANGE','suraj.thange@gmail.com','5478945987','1995-08-03');   EX.PRIMARY KEY NOT NULL

INSERT INTO BRANCHES (BARNCHID,BRANCHNAME,BRANCHADDRESS,BRANCHPHONENO)
VALUES (1,'MUMBAI MAIN BRANCH','ANDHERI EAST MUMBAI','0220100201'),
(2,'PUNE CENTAL BRANCH','CH SHIVAJI MAHARJ NAGAR PUNE','0220100202'),
(3,'BANGLORE BRANCH','MG ROAD BANGLORE','0880100801'),
(4,'DELHI BRANCH','CONNAUGHT PALACE DELHI',NULL),
(5,'HYDERABAD BRANCH',NULL,'0440100401');

select*
FROM BRANCHES;

 SET FOREIGN_KEY_CHECKS =0;
INSERT INTO ACCOUNTS 
VALUES  (1001,'Savings','25000',101,1),
(1002,'Savings','85000.50',102,2),
(1003,'Current','125000.75',103,1),
(1004,'Savings','45000',104,3),
(1005,'Salary','7800.30',105,2),
(1006,'Savings','42000',101,2),
(1007,'Current',NULL,103,3),
(1008,'Savings','27500',105,4);

select*
FROM ACCOUNTS;

INSERT INTO TRANSACTIONS 
VALUES(5001,'2026-01-04','10000','Deposit','1001'),
(5002,'2026-01-07','2500','Withdrawal','1001'),
(5003,'2026-01-09','5000','Transfer','1002'),
(5004,'2026-01-12','3000','Deposit','1003'),
(5005,'2026-01-15','3400','Withdrawl','1004'),
(5006,'2026-01-17','27000','Withdrawl','1005'),
(5007,NULL,'20000','Deposit','1006'),
(5008,'2026-02-10',NULL,'Transfer','1007'),
(5009,'2026-02-11','5000','Deposit','1008'),
(5010,'2026-02-15',Null,'Payment','1003'),
(5011,'2026-02-22','14000','Withdrwal','1003'),
(5012,'2026-03-02','52000','Salary','1003'),
(5013,'2026-03-08','1853','Payment','1003'),
(5014,'2026-03-12','8000','Deposit','1003'),
(5015,'2026-03-18','5000','Transfer','1003');

SELECT *
FROM TRANSACTIONS;

INSERT INTO TRANSACTIONS value(5016,NULL,3000,'Transfer','1004');
describe TRANSACTIONS;

INSERT INTO LOANS VALUES 
(9001,50000,8.50,'2025-01-15','2028-01-15',101),
(9002,250000,9.25,'2025-01-20','2037-01-20',102),
(9003,150000,9.00,'2025-01-28','2032-01-28',103),
(9004,750000,7.90,'2025-02-05','2050-02-05',104),
(9005,125000,8.25,'2025-02-15','2030-02-15',105),
(9006,250000,8.80,'2025-03-20','2037-03-20',103),
(9007,225000,9.15,'2025-03-21','2036-03-21',102);

SELECT*
FROM LOANS; 
SELECT*
FROM TRANSACTIONS; 
SELECT*
FROM ACCOUNTS; 
SELECT*
FROM BRANCHES;
SELECT*
FROM CUSTOMERS;  

UPDATE CUSTOMERS
SET PHONE = "8643267432"
WHERE CUSTOMERID = 105;  -- UPDATE PHONE NO 

UPDATE CUSTOMERS
SET BIRTHDATE ="1997-04-07"
WHERE CUSTOMERID=103;   -- UPDATE BIRTH DATE

DELETE FROM TRANSACTIONS
WHERE TRANSACTIONID = 5007; -- DELETED A USELESS DATA

UPDATE ACCOUNTS 
SET BALANCE = 27570
WHERE ACCOUNTID = 1007;

-- EXTRACING THE DATA

SELECT FIRSTNAME,EMAILID,CUSTOMERID
FROM CUSTOMERS;

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID=104; -- CALLING SPECIFIC DATA

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID=104 OR CUSTOMERID=101 OR CUSTOMERID=103; -- OR FUNCTION FOR CALLING MULTIPLE ID'S

SELECT * 
FROM CUSTOMERS
WHERE BIRTHDATE >='1995-01-01' AND BIRTHDATE <='1996-12-31';  -- AND FUNCTION

UPDATE TRANSACTIONS 
SET ACCOUNTID = 1006
WHERE TRANSACTIONID IN(5012,5014,5010);  --  IN FUNCTION UPDATE MULTIPLE RECORDS

-- CUSTOMER ANALYSIS
-- COUNT OF CUSTOMERS 
SELECT COUNT(*) AS TOTAL_CUSTOMERS  -- COLUMN ALISES
FROM CUSTOMERS;

-- WHICH CUSTOMER HAVE MISSING INFORMATION
SELECT CUSTOMERID,FIRSTNAME AS NAME
FROM CUSTOMERS
WHERE LASTNAME IS NULL OR EMAILID IS NULL OR PHONE IS NULL;
SELECT * FROM CUSTOMERS;

-- WHO ARE THE YOUNGEST/OLDEST CUTOMERS?
SELECT 
MAX(BIRTHDATE) AS YOUNGEST_CUSTOMER,
MIN(BIRTHDATE) AS OLDEST_CUSTOMERS
FROM CUSTOMERS;

-- HOW MANY CUSTOMERS BORN BEFORE/AFTER A PARTICULAR YEAR
-- BEFORE 2000
SELECT *
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE)<= 2000;

-- AFTER 2000
SELECT *
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE)>2000;

-- WHICH CUSTOMER HAVE MULTIPLE ACCOUNTS

SELECT  CUSTOMERID,COUNT(*) AS Total_Accounts
FROM ACCOUNTS
GROUP BY  CUSTOMERID
HAVING Total_Accounts>1;

-- ACCOUNT ANALYSIS
-- HOW MANY SAVING ,CURRENT AND SALARY ACCOUNTS EXIST

SELECT ACCOUNTTYPE, COUNT(*) AS Total_Accounts
FROM ACCOUNTS
GROUP BY ACCOUNTTYPE;

-- WHAT IS TOTAL BALANCE 
SELECT SUM(BALANCE)  Total_Balance
FROM ACCOUNTS;

-- WHAT IS AVERAGE ACCOUNT BALANCE 
SELECT AVG(BALANCE) Average_Balance
FROM ACCOUNTS;

-- WHICH CUSTOMER HAVE THE HIGHEST BALANCE

SELECT CUSTOMERID, BALANCE Highest_Balance
FROM ACCOUNTS
ORDER BY BALANCE DESC LIMIT 1;

-- WHICH ACCOUNT HAVE NULL BALANCE 

SELECT *
FROM ACCOUNTS
WHERE BALANCE=NULL;

-- WHICH BRANCH MANAGES THE MOST ACCOUNTS

SELECT BRANCHID,COUNT(*) Total_Accounts
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Accounts DESC LIMIT 1;

-- TRANSACTION ANALYSIS
--  WHAT IS TOTAL TRANSACTION AMOUNT

SELECT SUM(AMOUNT) TOTAL_TRANSACTION_AMOUNT
FROM TRANSACTIONS;

-- HOW  MANY DEPOSITS/WIITHDRWAL/TRANSFERS ARE THERE

SELECT TRANSACTIONTYPE,COUNT(*) Total_Transactions
FROM TRANSACTIONS
WHERE TRANSACTIONTYPE IN ('DEPOSIT','WITHDRAWAL','TRANSFER')
GROUP BY TRANSACTIONTYPE;

-- WHICH TRANSACTION TYPE HAS THE HIGHEST VOLUME
SELECT TRANSACTIONTYPE,SUM(AMOUNT) Total_Amount
FROM TRANSACTIONS
GROUP BY TRANSACTIONTYPE
ORDER BY Total_Amount DESC LIMIT 1;

-- WHAT IS AVERAGE TRANSACTION AMOUNT
SELECT AVG(BALANCE) Average_Transaction_Balance
FROM TRANSACTIONS;

-- WHICH ACCOUNT HAS THE HIGHEST TRANSACTION ACTIVITY
SELECT ACCOUNTID, COUNT(*) Total_Transactions
FROM TRANSACTIONS
GROUP BY ACCOUNTID
ORDER BY Total_Transactions DESC LIMIT 1;

-- WHICH TRANSACTIONS HAVE MISSING DATES/AMOUNTS
SELECT*
FROM TRANSACTIONS 
WHERE TRANSACTIONDATE IS NULL OR AMOUNT IS NULL;

-- LOAN ANALYSIS
-- WHAT IS TOTAL LOAN AMOUNT

SELECT SUM(LOANAMOUNT) Total_Loan_Amount
FROM LOANS;

-- WHICH CUSTOMER HAS THE LARGEST LOAN
 SELECT CUSTOMERID,MAX(LOANAMOUNT) Total_Loan
 FROM LOANS
 GROUP BY CUSTOMERID
 ORDER BY Total_Loan DESC LIMIT 1;
 
 -- WHICH LOAN HAS THE HIGHEST INTREST RATE
SELECT LOANID, MAX(INTRESTRATE) Highest_Intrest_Rate
FROM LOANS
GROUP BY LOANID
ORDER BY Highest_Intrest_Rate DESC LIMIT 1;

-- WHAT IS AVERAGE LOAN AMOUNT
SELECT AVG(LOANAMOUNT) Average_Loan_Amount
FROM  LOANS;

-- WHICH CUSTOMER HAVE MULTIPLE LOANS
SELECT CUSTOMERID, COUNT(LOANID) TOTAL_LOANS
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY TOTAL_LOANS DESC LIMIT 1;

-- WHICH LOANS ARE STILL ACTIVE
SELECT *
FROM LOANS
WHERE ENDDATE>2026-10-09;

-- BRANCH ANALYSIS
-- WHICH BRANCH HAS THE MOST CUSTOMERS/ACCOUNTS

SELECT BRANCHID,COUNT(ACCOUNTID) Total_Accounts  -- BRANCH WITH MOST ACCOUNTS
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Accounts DESC LIMIT 1;

SELECT BRANCHID,COUNT(CUSTOMERID) Total_Customers -- BRANCH WITH MOST CUSTOMERS
FROM ACCOUNTS 
GROUP BY BRANCHID 
ORDER BY Total_Customers DESC LIMIT 1;

-- WHICH BRANCH HAS THE HIGHEST TOTAL ACCOUNT BALANCE
SELECT BRANCHID, SUM(BALANCE) Total_Account_Balance
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Account_Balance DESC LIMIT 1;

-- WHICH BRANCH HANDLE THE MOST TRANSACTION
SELECT ACCOUNTID, COUNT(*) Total_Transactions   -- ACCOUNT WITH MAX TRANSACTION
FROM TRANSACTIONS
GROUP BY ACCOUNTID
ORDER BY Total_Transactions DESC LIMIT 1;

SELECT BRANCHID                     -- BRANCH WITH MAX TRANSACTION
FROM ACCOUNTS
WHERE ACCOUNTID=1003;

-- WHICH BRANCH HAS HIGHEST LOAN EXPOSURE
SELECT CUSTOMERID, SUM(LOANAMOUNT)  Total_Highest_Loan   -- CUSTOMER WITH MAX LOAN AMOUNT
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY Total_Highest_Loan DESC LIMIT 1;

SELECT BRANCHID      -- BRANCH WITH MAX LOAN AMOUNT
FROM ACCOUNTS 
WHERE CUSTOMERID=104;

SELECT* 
FROM BRANCHES;

                           -- STRING FUNCTION
                           
SELECT CUSTOMERID , concat(FIRSTNAME," ",LASTNAME) FULL_NAME            -- CONCAT()
FROM CUSTOMERS;

SELECT CUSTOMERID , UPPER(concat(FIRSTNAME," ",LASTNAME)) FULL_NAME            -- UPPER()
FROM CUSTOMERS;

SELECT CUSTOMERID , LOWER(concat(FIRSTNAME," ",LASTNAME)) FULL_NAME            -- LOWER()
FROM CUSTOMERS;

SELECT FIRSTNAME, LENGTH(FIRSTNAME) AS NAME_LENGTH       -- LENGTH()
FROM CUSTOMERS
HAVING NAME_LENGTH>4
ORDER BY NAME_LENGTH DESC LIMIT 1 OFFSET 1;   -- OFFSET IS USED TO SKIP THE VALUES

SELECT FIRSTNAME, CHAR_LENGTH(FIRSTNAME) AS CHARACTER_LENGTH       -- CHAR_LENGTH()
FROM CUSTOMERS;

SELECT FIRSTNAME, LEFT(FIRSTNAME,3) FIRST_3_CHARACTER     -- LEFT()
FROM CUSTOMERS;

SELECT PHONE, RIGHT(PHONE,4) LAST4DIGITS                  -- RIGHT()
FROM CUSTOMERS;

SELECT CUSTOMERID, CONCAT("XXXXXX",RIGHT(PHONE,4)) MASKEDPHONENO                  -- CONCAT() & RIGHT()
FROM CUSTOMERS;

						-- SUBSTRING 
                        
SELECT EMAILID, SUBSTRING(EMAILID,1,5) EMAIL_PART
FROM CUSTOMERS;
                                                                         -- SUBSTRING_INDEX
SELECT EMAILID, SUBSTRING_INDEX(EMAILID,"@",1) EMAIL_PART    -- 1 BEFORE SPECIFIC CHAR ,-1 FOR AFTER SPECIFIC CHAR
FROM CUSTOMERS;

SELECT TRIM("SURAJ THANGE        ") NAME;              -- TRIM()    REMOVE UNESSESARY SPACE (NOT BETWEEN TEXT)

SELECT EMAILID, REPLACE(EMAILID,'gmail.com','email.com') EMAILS     -- REPLACE
FROM CUSTOMERS;

SELECT EMAILID , LOCATE("@",EMAILID) POSITION                -- LOCATE POSITION 
FROM CUSTOMERS;

SELECT EMAILID, REPLACE(EMAILID,'email.com','gmail.com') EMAILS     -- REPLACE
FROM CUSTOMERS;

                          -- MATH FUNCTION

SELECT ACCOUNTID,BALANCE,ROUND(BALANCE,0) ROUNDED_BALANCE      -- ROUND (ROUNDS OFF DECIMAL VALUE)
FROM ACCOUNTS;

SELECT BALANCE,CEIL(BALANCE) ROUNDUP_BALANCE              -- CEIL/CELING  (IT ROUNDS UP THE VALUE)
FROM ACCOUNTS;

SELECT BALANCE,FLOOR(BALANCE) ROUNDUP_BALANCE              -- FLOOR  (IT ROUNDS DOWN THE VALUE)
FROM ACCOUNTS;

SELECT ABS(-57889) ABSOLUTE_VALUE;                       -- ABS (RETURNS ABSOLUTE VALUE (+VALUE))

SELECT ACCOUNTID,MOD(ACCOUNTID,2) REMINDER              -- MOD RETURNS THE REMANING VALUE
FROM ACCOUNTS;

SELECT ACCOUNTID, MOD(ACCOUNTID,2) REMINDER , CASE           -- CASE THENEND IS JUST LIKE IF-ELSE STATMENT
WHEN MOD(ACCOUNTID,2)=0 THEN "Even"
ELSE "Odd"
END ID_TYPE
FROM ACCOUNTS;

SELECT POWER(2,4) RESULT;                              -- POWER  (WORKS LIKE INDICES)

SELECT BALANCE,SQRT(BALANCE) SQRT_BALANCE              -- SQRT (RETURNS SQUARE ROOT)
FROM ACCOUNTS;

SELECT ACCOUNTID,BALANCE,GREATEST(BALANCE,25000) MIN_BALANCE        -- GREATEST (COMPARE VALUES)
FROM ACCOUNTS;

SELECT ACCOUNTID,BALANCE,LEAST(BALANCE,45000) MAX_BALANCE        -- LEAST (COMPARE VALUES)
FROM ACCOUNTS;

          -- CALCULATE ANNUAL INTREST
SELECT LOANID,LOANAMOUNT,INTRESTRATE, ROUND(LOANAMOUNT*INTRESTRATE/100,2) ANNUAL_INTREST
FROM LOANS;

           -- LOAN AMOUNT + INTRESTRATE
SELECT LOANID,LOANAMOUNT,INTRESTRATE,
 ROUND((LOANAMOUNT)+LOANAMOUNT*INTRESTRATE/100,0) PRINCIPAL_PLUS_ONEYEAR_INTEREST
FROM LOANS;

SELECT ACCOUNTID,BALANCE,                                       -- BALANCE CATEGORY
CASE
WHEN BALANCE IS NULL THEN "Unkown"
WHEN BALANCE < 10000 THEN "Low"
WHEN BALANCE < 50000 THEN "Medium"  
ELSE "High"
END BALANCE_CATEGORY
FROM ACCOUNTS;

                -- DATE & TIME FUNCTION 
SELECT CURDATE() TODAY;              -- TODAY'S DATE
SELECT SYSDATE() TODAY;              -- TODAY'S DATE WITH TIIME

SELECT CUSTOMERID,BIRTHDATE, YEAR(BIRTHDATE) BIRTH_YEAR              -- YEAR(EXTRACT YEAR FROM DATA)            
FROM CUSTOMERS;

SELECT TRANSACTIONID,TRANSACTIONDATE,MONTH(TRANSACTIONDATE) TRANSACTION_MONTH    -- MONTH(EXTRACT MONTH NO)
FROM TRANSACTIONS;            

SELECT TRANSACTIONID,TRANSACTIONDATE,MONTHNAME(TRANSACTIONDATE) TRANSACTION_MONTH   -- MONTHNAME(EXTRACT MONTH NAME)
FROM TRANSACTIONS;    

SELECT TRANSACTIONID,TRANSACTIONDATE,DAY(TRANSACTIONDATE) TRANSACTION_DAY_NO                 -- DAY(EXTRACT DAY NO)
FROM TRANSACTIONS;    

SELECT TRANSACTIONID,TRANSACTIONDATE,DAYNAME(TRANSACTIONDATE) TRANSACTION_DAY_NAME   -- DAYNAME(EXTRACT DAY NAME)
FROM TRANSACTIONS;   

SELECT TRANSACTIONID,TRANSACTIONDATE,QUARTER(TRANSACTIONDATE) QUARTER_NO  -- QUARTER(EXTRACT QUARTER NO)
FROM TRANSACTIONS; 

SELECT QUARTER(TRANSACTIONDATE) QUATERS, COUNT(*) TRANSACTION_COUNT,   
SUM(AMOUNT) TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY QUARTER(TRANSACTIONDATE);

SELECT LOANID,STARTDATE,ENDDATE,DATEDIFF(ENDDATE,STARTDATE) LOAN_DAYS         -- DATEDIFF (DIFFERNCE BTW DATES)
FROM LOANS;

SELECT LOANID,STARTDATE,ENDDATE,ROUND(DATEDIFF(ENDDATE,STARTDATE)/365,2) LOAN_YEARS         
FROM LOANS;

SELECT LOANID,STARTDATE,ENDDATE,DATEDIFF(CURDATE(),STARTDATE) LOAN_DAYS        
FROM LOANS;

SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AGE     -- TIMESTAMPDIFF
FROM CUSTOMERS;

SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,                             -- AGE_GROUP
TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AGE,
CASE
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE())<25 THEN "Young Adult"
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE())BETWEEN 25 AND 40  THEN "Adult"
ELSE "Senior"
END AGE_GROUP
FROM CUSTOMERS;

SELECT TRANSACTIONDATE,DATE_FORMAT(TRANSACTIONDATE,'%d-%m-%y') FORMATED_DATE            -- DATE_FORMAT 
FROM TRANSACTIONS;

SELECT TRANSACTIONDATE,DATE_FORMAT(TRANSACTIONDATE,'%D-%M-%Y') FORMATED_DATE
FROM TRANSACTIONS;

SELECT                                                  -- MONTHLY TRANSACTIONS
DATE_FORMAT(TRANSACTIONDATE,'%Y-%m')  MONTH,
COUNT(*)  TRANSACTION_COUNTS,
SUM(AMOUNT)  TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY DATE_FORMAT(TRANSACTIONDATE,'%Y-%m') 
ORDER BY MONTH;

SELECT *                                  -- LAST 30 DAYS TRANSACTIONS
FROM TRANSACTIONS
WHERE TRANSACTIONDATE >= DATE_SUB('2026-02-25',INTERVAL 30 DAY) ;

SELECT TRANSACTIONID,TRANSACTIONDATE, DATE_ADD(TRANSACTIONDATE,INTERVAL 30 DAY) AFTER_30_DAYS
FROM TRANSACTIONS;

SELECT LOANID, STARTDATE,ENDDATE,                  -- LOAN STATUS USING DAYS
CASE
WHEN ENDDATE IS NULL THEN "NO END DATE"
WHEN ENDDATE <CURDATE()THEN "COMPLETED"
ELSE "ACTIVE"
END AS LOAN_STATUS
FROM LOANS;

                             -- WINDOWS FUNCTION 
SELECT LOANID,LOANAMOUNT, RANK() OVER(ORDER BY LOANAMOUNT DESC)  LOAN_RANK           -- RANK() & OVER()
FROM LOANS; 
 
SELECT LOANID,LOANAMOUNT,                                                     
RANK() OVER(ORDER BY LOANAMOUNT DESC)  LOAN_RANK ,  
DENSE_RANK() OVER(ORDER BY LOANAMOUNT DESC) LOAN_DENS_RANK            -- DENS_RANK(NEVER SKIP RANK VALUE)
FROM LOANS; 
 
SELECT TRANSACTIONID,TRANSACTIONTYPE,AMOUNT,                                             -- PARTITION BY(CATEGORIZE DATA)
DENSE_RANK() OVER(PARTITION BY TRANSACTIONTYPE ORDER BY AMOUNT DESC)  TRANSACTION_RANK
FROM TRANSACTIONS;
 
SELECT LOANID,CUSTOMERID,LOANAMOUNT,                                     -- ROW_NUMBER()
ROW_NUMBER() OVER(ORDER BY LOANAMOUNT DESC) ROWNUMBER
FROM LOANS; 

SELECT LOANID,CUSTOMERID,LOANAMOUNT,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERID ORDER BY LOANAMOUNT DESC) ROWNUMBER
FROM LOANS;

SELECT TRANSACTIONID,AMOUNT,                                  -- SUM() CALCULATE RUNNING TOTAL
SUM(AMOUNT) OVER(ORDER BY AMOUNT DESC) RUNNING_TOTAL
FROM TRANSACTIONS;

SELECT LOANID, CUSTOMERID, LOANAMOUNT,
SUM(LOANAMOUNT) OVER(ORDER BY LOANAMOUNT DESC) RUNNING_TOTAL
FROM LOANS;

SELECT LOANID,CUSTOMERID,LOANAMOUNT,                                    -- LAG() CHECK PREVIOUS VALUES
LAG(LOANAMOUNT) OVER(ORDER BY LOANAMOUNT DESC) PREVIOUS_LOANAMOUNT
FROM LOANS;

SELECT LOANID,CUSTOMERID,LOANAMOUNT,                                     -- LEAD() CHECK AFTER VALUES
LEAD(LOANAMOUNT) OVER(ORDER BY LOANAMOUNT DESC) NEXT_LOANAMOUNT
FROM LOANS;

SELECT LOANID,CUSTOMERID,LOANAMOUNT,                                
LEAD(LOANAMOUNT) OVER(PARTITION BY CUSTOMERID ORDER BY LOANAMOUNT DESC) NEXT_LOANAMOUNT
FROM LOANS;





